spring:
  datasource:
    url: jdbc:h2:mem:desafio.sdw2023
    username: user
    password:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false